### ISSUE TITLE
versioning problem

### ISSUE THREAD

**Issue by meysamhadeli** [mizrael/SuperSafeBank#3]
Hi.
why in classs EventsRepository and method AppendAsync, doesn't use expected_version: any or expected_version: auto!?
```csharp
  var firstEvent = aggregateRoot.Events.First();
  var version = firstEvent.AggregateVersion - 1;

  using var transaction = await connection.StartTransactionAsync(streamName, version);
```

**Comment by mizrael** [comment]
hi! Because we want to ensure that we expect the Events stream to be in a specific position. The goal is to prevent any possible concurrency issue ( the same command being triggered twice for example)

**Comment by meysamhadeli** [comment]
why firstEvent.AggregateVersion - 1? why not firstEvent.AggregateVersion?

**Comment by mizrael** [comment]
`firstEvent.AggregateVersion` contains the *current* Aggregate version. We are checking against what's stored in the db instead, which obviously, still doesn't contain the latest updates we've done with our command
