### ISSUE TITLE
The option IntHttpPort is not a known option. (Parameter 'IntHttpPort')

### ISSUE THREAD

**Issue by Seany84** [mizrael/SuperSafeBank#5]
After cloning and running `docker-compose up` I was getting an error message: `The option IntHttpPort is not a known option. (Parameter 'IntHttpPort')`

I believe changing the `docker-compose.yml` to this will correct the issue: 

>    environment:
>       - EVENTSTORE_CLUSTER_SIZE=1
>       - EVENTSTORE_INT_TCP_PORT=1112
>       - EVENTSTORE_EXT_TCP_PORT=1113
>       - EVENTSTORE_HTTP_PORT=2113

**Comment by mizrael** [comment]
hi @Seany84, apologies for the (extremely) late reply! I am doing a lot of changes to the project and I'm pretty sure this issue is fixed now. Can you confirm? Thanks!
